config/routes.rb
Rails.application.routes.draw do

  devise_for :users

 resources :lists, only: [:new, :create, :show]
 resources :items, only: [:new, :create, :show, :destroy]

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

   root "welcome#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  def days_left
    7 - ( (Time.now - created_at)/(60*60*24) ).to_i
  end

  def prune_list
    Item.where("created_at <= ?", Time.now - 7.days).destroy_all
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user
  
  def prune_list
    Item.where("created_at <= ?", Time.now - 7.days).destroy_all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :trackable, :validatable
  
  has_one :list

  after_create :add_list

  private

  def add_list
    list = List.new(title: "#{name}'s List", user_id: id).save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

     def hello
     render text: "<h1>Hello</h1><p>Welcome home</p>"
   end

   
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 
  def new
  end

  def create
    @list = current_user.list
    @item = @list.items.build(item_params)
    @item.save!
    redirect_to @list
  end

  def destroy
    @item = Item.find(params[:id])
    @list = @item.list
    if @item.destroy
     flash[:notice] = "Item deleted."
    else
      flash[:error] = "Error deleting the item. Please try again."
    end

    redirect_to @list

  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  
  def show
    @list = List.find params[:id]
  end

  private

  def item_params
    params.require(:list).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @item = Item.new
  end


  private
 
   def user_params
     params.require(:user).permit(:name)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to current_user.list if current_user 
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/new.html.erb
<h2>Add new item</h2>
<%= form_for Item.new do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.submit 'Save' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     <div class="container">

       <ul class="nav nav-tabs">


         <div class="pull-right user-info">
           <% if current_user %>
            Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

<%= yield %>

</body>
</html>

app/views/lists/new.html.erb
<%= form_for List.new do |form| %>
  <%= form.text_field :title, placeholder: 'Title' %>
  <%= form.submit 'Save' %>
<% end %>

app/views/lists/show.html.erb
<h1><%= current_user.list.title %></b></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Days Remaining</th>
      <th>Complete</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.list.items.each do |item| %>
      <tr>
        <td>
          <%= item.name %><br/>
        </td>
        <td>   
          <%= item.days_left %><br/>
        </td>
        <td>
          <%= link_to(item, method: :delete) do %>
            <input type="checkbox"><br/>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add item", new_item_path, class: 'btn btn-primary' %>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/show.html.erb
 <div class="row">
   <div class="col-md-8">
     <div class="media">

       <div class="media-body">
         <h2 class="media-heading"><%= @user.name %></h2>
         <h2 class="media-heading"><%= @user.email %></h2>
       </div>
     </div>
   </div>
 </div>

<ul>
  <% @user.items.each do |i| %>
    <li><%= i.name %></li>
  <% end %>
</ul>

<%= render "items/form.html.erb" %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>CheckitOff</h1>
  <p>CheckitOff helps you out!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>